### ISSUE TITLE
Language server fails to start

### ISSUE THREAD

**Issue by jcmrva** [CircleCI-Public/circleci-yaml-language-server#181] opened 2023-06-06 12:04 UTC
I just started using the CircleCI extension. The language server doesn't start because:

```
Error while loading JSON Schema "C:\Users\___\AppData\Local\Programs\Microsoft VS Code/C:\Users\___\AppData\Local\CircleCI-language-server\Data\schema.json"
open C:\Users\___\AppData\Local\Programs\Microsoft VS Code\C:\Users\___\AppData\Local\CircleCI-language-server\Data\schema.json: The filename, directory name, or volume label syntax is incorrect.
```

Is there a way to correct the path in a config somewhere?

VS Code: 1.78.2
Language server: 0.5.2
CircleCI extension: 1.13.3
OS: Windows 10

**Comment by abdelDriowya** [comment] 2023-06-14 13:47
Hi @jcmrva thanks for reporting this.
The issue is related to our release process we're working on solving it.
Normally the issue should go away when you reload your Vscode.

**Comment by BeFunes** [comment] 2023-06-14 14:41
Hi @jcmrva, can you just confirm if you are still seeing the problem after reloading VS Code? 
If so I think we can close the issue right @abdelDriowya?

**Comment by jcmrva** [comment] 2023-06-14 14:46
I'm fairly certain I had restarted Code at least once after I initially saw the error message, but it is working now. Thanks!

**Closed** 2023-07-04 08:14 UTC
